"""Initial migration

Revision ID: 5c9e542b3fa3
Revises: 0ceee3f09f67
Create Date: 2025-08-14 15:57:55.232598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9e542b3fa3'
down_revision: Union[str, Sequence[str], None] = '0ceee3f09f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'lng')
    op.drop_column('media', 'lat')
    # ### end Alembic commands ###
