"""Add verification fields to media table

Revision ID: 9c8b7a6d5f4e
Revises: jfileajfje34384
Create Date: 2025-08-20 10:15:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8b7a6d5f4e'
down_revision = 'jfileajfje34384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('verification_status', sa.String(), nullable=False, server_default='UNVERIFIED'))
    op.add_column('media', sa.Column('signature', sa.LargeBinary(), nullable=True))
    op.add_column('media', sa.Column('public_key', sa.LargeBinary(), nullable=True))
    op.add_column('media', sa.Column('client_media_hash', sa.String(), nullable=True))
    op.add_column('media', sa.Column('client_metadata_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'client_metadata_hash')
    op.drop_column('media', 'client_media_hash')
    op.drop_column('media', 'public_key')
    op.drop_column('media', 'signature')
    op.drop_column('media', 'verification_status')
    # ### end Alembic commands ###
