"""Add orientation vector to media table

Revision ID: a1b2c3d4e5f6
Revises: add_location_column
Create Date: 2025-8-16 8:56:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'add_location_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('orientation_azimuth', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('orientation_pitch', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('orientation_roll', sa.Float(), nullable=True))
    op.drop_column('media', 'orientation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('orientation', sa.FLOAT(), autoincrement=False, nullable=True))
    op.drop_column('media', 'orientation_roll')
    op.drop_column('media', 'orientation_pitch')
    op.drop_column('media', 'orientation_azimuth')
    # ### end Alembic commands ###
