"""Initial migration

Revision ID: bdc26436cf0c
Revises: 373336946331
Create Date: 2025-08-14 19:07:34.008941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc26436cf0c'
down_revision: Union[str, Sequence[str], None] = '373336946331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('orientation', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('trust_score', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'file_path')
    op.drop_column('media', 'trust_score')
    op.drop_column('media', 'orientation')
    # ### end Alembic commands ###
