"""Initial migration

Revision ID: eb6845fcc5c9
Revises: bdc26436cf0c
Create Date: 2025-08-14 19:13:33.129721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6845fcc5c9'
down_revision: Union[str, Sequence[str], None] = 'bdc26436cf0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('capture_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'capture_time')
    # ### end Alembic commands ###
