"""
Add thumbnail_path to Media table

Revision ID: jfileajfje34384
Revises: a1b2c3d4e5f6
Create Date: 2025-8-19 7:43:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Import if using Geography type, otherwise optional

# revision identifiers, used by Alembic.
revision = 'jfileajfje34384'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'thumbnail_path')
    # ### end Alembic commands ###

